services:
  gasbuddy-scraper:
    image: localhost/gasbuddy-scraper:latest
    container_name: gasbuddy-scraper
    ports:
      - 5000:5000
    volumes:
      - ./websites.db:/app/websites.db
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
